[tool.poetry]
name = "curso-django"
version = "0.1.0"
description = ""
authors = ["bpascoal"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^10.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
